# Generated by Django 4.2 on 2024-07-13 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('genre', models.CharField(max_length=15)),
                ('director', models.CharField(max_length=30)),
                ('release_year', models.CharField(max_length=12)),
                ('sinopsis', models.TextField(max_length=300)),
            ],
        ),
    ]
